Update README.md
lumapps-marketplace/lumapps-extension-code-sample pull request #13
Opened 2024-11-05 14:36 UTC by grentlich

2024-11-05 14:39 UTC, gregorycat requested changes

2024-11-05 14:39 UTC, gregorycat commented on micro-app/ServiceNow ticket list/README.md
> +## Step 1: Get the end user s
```suggestion
## Step 1: Get the end users
```

2024-11-05 14:39 UTC, gregorycat commented on micro-app/ServiceNow ticket list/README.md
> +/api/now/table/incident?sysparm_limit=5&sysparm_query=caller_id=${actions.getuser.response.body.result[0].sys_id}^stateNOT%20IN7
Are you sure of this URL ? the `^` is uncommon

2024-11-05 14:47 UTC, Georgina-gh approved these changes
I made some suggestions because there is a typo in the step 1 title and so that hopefully the endpoints can have the code styling applied (`..`)

2024-11-05 14:47 UTC, Georgina-gh commented on micro-app/ServiceNow ticket list/README.md
> +## Step 1: Get the end user s
```suggestion
## Step 1: Get the end user's email
```

2024-11-05 14:47 UTC, Georgina-gh commented on micro-app/ServiceNow ticket list/README.md
> +Create an API Call named `getuser` according to the following endpoint as a GET Method:
```suggestion
Create an API Call named `getuser` using the following endpoint, with the GET Method:
```

2024-11-05 14:47 UTC, Georgina-gh commented on micro-app/ServiceNow ticket list/README.md
> +/api/now/table/sys_user?sysparm_query=email=${user.email}
```suggestion
`/api/now/table/sys_user?sysparm_query=email=${user.email}`
```

2024-11-05 14:47 UTC, Georgina-gh commented on micro-app/ServiceNow ticket list/README.md
> +/api/now/table/incident?sysparm_limit=5&sysparm_query=caller_id=${actions.getuser.response.body.result[0].sys_id}^stateNOT%20IN7
```suggestion
`/api/now/table/incident?sysparm_limit=5&sysparm_query=caller_id=${actions.getuser.response.body.result[0].sys_id}^stateNOT%20IN7`
```

2024-11-06 10:59 UTC, grentlich commented
ok go

2024-11-06 11:28 UTC, Georgina-gh commented on micro-app/ServiceNow ticket list/README.md
> +/api/now/table/incident?sysparm_limit=5&sysparm_query=caller_id=${actions.getuser.response.body.result[0].sys_id}^stateNOT%20IN7
@grentlich check if you made an error in the endpoint:
/api/now/table/incident?sysparm_limit=5&sysparm_query=caller_id=${actions.getuser.response.body.result[0].sys_id}^stateNOT%20IN7

If you are sure the endpoint is tested and correct you can add a comment to confirm this.

2024-11-06 11:30 UTC, Georgina-gh commented on micro-app/ServiceNow ticket list/README.md
> +## Step 1: Get the end user s
@grentlich commit my or Gregory's suggestion (click "commit suggestion") or make your own changes to fix the typo

2024-11-06 13:13 UTC, grentlich commented on micro-app/ServiceNow ticket list/README.md
> +/api/now/table/incident?sysparm_limit=5&sysparm_query=caller_id=${actions.getuser.response.body.result[0].sys_id}^stateNOT%20IN7
oui

2024-11-06 13:15 UTC, gregorycat approved these changes

2024-11-06 13:15 UTC, merged